version: '3.1'

services:
  s_apigateway:
    container_name: c_apigateway
    image: busraakay/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    networks:
      - net_api
      - int_net_api
    ports:
      - 8081:80

  s_contact_api:
    container_name: c_contact_api
    image: busraakay/contactapi
    build:
      context: .
      dockerfile: Services/ContactAPI/Contact.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 6000:6000

  s_res_api:
    container_name: c_res_api
    image: busraakay/resapi
    build:
      context: .
      dockerfile: Services/ResAPI/Reservation.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 7000:7000


networks:
  net_api:
    driver: bridge

  int_net_api:
    driver: bridge
    internal: true